version: '3.8'

services:
  jenkins:
    image: jenkins/jenkins:2.440.3-lts
    container_name: jenkins-server
    ports:
      - "8081:8080"
      - "50000:50000"
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
      - ./:/workspace
    environment:
      - JENKINS_OPTS=--httpPort=8080
    networks:
      - jenkins
    restart: unless-stopped

  docker-in-docker:
    image: docker:24.0.7-dind
    container_name: jenkins-docker
    privileged: true
    networks:
      jenkins:
        aliases:
          - docker
    environment:
      - DOCKER_TLS_CERTDIR=/certs
    volumes:
      - jenkins-docker-certs:/certs/client
      - jenkins_home:/var/jenkins_home
    ports:
      - "2376:2376"
    command: --storage-driver overlay2

volumes:
  jenkins_home:
  jenkins-docker-certs:

networks:
  jenkins:
    driver: bridge 