apiVersion: v1
kind: ConfigMap
metadata:
  name: user-service-config
  namespace: ecommerce-prod
  labels:
    app: user-service
    environment: production
data:
  application.yml: |
    server:
      port: 8087
    spring:
      profiles:
        active: prod
      datasource:
        url: jdbc:mysql://mysql-prod:3306/ecommerce_user_db
        username: ${MYSQL_USER}
        password: ${MYSQL_PASSWORD}
        driver-class-name: com.mysql.cj.jdbc.Driver
      jpa:
        hibernate:
          ddl-auto: validate
        show-sql: false
        properties:
          hibernate:
            dialect: org.hibernate.dialect.MySQL8Dialect
            format_sql: false
      flyway:
        enabled: true
        baseline-on-migrate: true
    eureka:
      client:
        service-url:
          defaultZone: http://service-discovery:8761/eureka/
      instance:
        prefer-ip-address: true
    management:
      endpoints:
        web:
          exposure:
            include: health,info,metrics
      endpoint:
        health:
          show-details: always
    logging:
      level:
        com.selimhorri: INFO
        org.springframework.security: WARN
        org.hibernate.SQL: ERROR 