apiVersion: v1
kind: Service
metadata:
  name: order-service
  namespace: ecommerce-prod
  labels:
    app: order-service
    version: v1
    environment: production
spec:
  type: LoadBalancer
  ports:
  - port: 8083
    targetPort: 8083
    protocol: TCP
    name: http
  selector:
    app: order-service
---
apiVersion: v1
kind: Service
metadata:
  name: order-service-internal
  namespace: ecommerce-prod
  labels:
    app: order-service
    version: v1
    environment: production
    purpose: internal
spec:
  type: ClusterIP
  ports:
  - port: 8083
    targetPort: 8083
    protocol: TCP
    name: http
  selector:
    app: order-service 