apiVersion: v1
kind: ConfigMap
metadata:
  name: payment-service-config
  namespace: ecommerce
  labels:
    app: payment-service
    version: v1
data:
  application.properties: |
    # Payment Service Configuration
    server.port=8084
    spring.application.name=payment-service
    
    # Database Configuration
    spring.datasource.url=jdbc:h2:mem:paymentdb
    spring.datasource.driver-class-name=org.h2.Driver
    spring.datasource.username=sa
    spring.datasource.password=
    spring.h2.console.enabled=true
    spring.jpa.hibernate.ddl-auto=create-drop
    spring.jpa.show-sql=true
    
    # Eureka Configuration
    eureka.client.service-url.defaultZone=http://service-discovery:8761/eureka/
    eureka.client.register-with-eureka=true
    eureka.client.fetch-registry=true
    eureka.instance.prefer-ip-address=true
    eureka.instance.hostname=${HOSTNAME:payment-service}
    
    # Management Endpoints
    management.endpoints.web.exposure.include=health,info,metrics,prometheus
    management.endpoint.health.show-details=always
    management.health.circuitbreakers.enabled=true
    management.health.ratelimiters.enabled=true
    
    # Logging
    logging.level.com.ecommerce.payment=DEBUG
    logging.level.root=INFO
    logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss} - %msg%n
    
    # Payment Gateway Configuration
    payment.gateway.stripe.api-key=${STRIPE_API_KEY:sk_test_dummy}
    payment.gateway.stripe.webhook-secret=${STRIPE_WEBHOOK_SECRET:whsec_dummy}
    payment.gateway.paypal.client-id=${PAYPAL_CLIENT_ID:dummy_client_id}
    payment.gateway.paypal.client-secret=${PAYPAL_CLIENT_SECRET:dummy_secret}
    payment.gateway.timeout=30000
    
    # Circuit Breaker
    resilience4j.circuitbreaker.instances.stripe.slidingWindowSize=10
    resilience4j.circuitbreaker.instances.stripe.failureRateThreshold=50
    resilience4j.circuitbreaker.instances.stripe.waitDurationInOpenState=30000
    
    resilience4j.circuitbreaker.instances.paypal.slidingWindowSize=10
    resilience4j.circuitbreaker.instances.paypal.failureRateThreshold=50
    resilience4j.circuitbreaker.instances.paypal.waitDurationInOpenState=30000
    
    # Rate Limiting
    resilience4j.ratelimiter.instances.payment-processing.limitForPeriod=100
    resilience4j.ratelimiter.instances.payment-processing.limitRefreshPeriod=60s
    resilience4j.ratelimiter.instances.payment-processing.timeoutDuration=10s
    
    # Microservices URLs
    microservices.order-service.url=http://order-service:8083
    microservices.user-service.url=http://user-service:8087 