apiVersion: v1
kind: Secret
metadata:
  name: payment-secrets
  namespace: ecommerce
type: Opaque
stringData:
  stripe-api-key: "sk_test_dummy_key"
  stripe-webhook-secret: "whsec_dummy_secret"
  paypal-client-id: "dummy_client_id"
  paypal-client-secret: "dummy_client_secret"
---
apiVersion: v1
kind: Secret
metadata:
  name: payment-db-secret
  namespace: ecommerce
type: Opaque
stringData:
  username: "paymentuser"
  password: "paymentpass"
