apiVersion: v1
kind: Service
metadata:
  name: payment-service
  namespace: ecommerce
  labels:
    app: payment-service
    version: v1
spec:
  type: NodePort
  ports:
  - port: 8084
    targetPort: 8084
    nodePort: 30084
    protocol: TCP
    name: http
  selector:
    app: payment-service 