apiVersion: apps/v1
kind: Deployment
metadata:
  name: proxy-client
  namespace: ecommerce
  labels:
    app: proxy-client
    version: v1
spec:
  replicas: 2
  selector:
    matchLabels:
      app: proxy-client
  template:
    metadata:
      labels:
        app: proxy-client
        version: v1
    spec:
      containers:
      - name: proxy-client
        image: proxy-client-ecommerce:{{BUILD_NUMBER}}
        imagePullPolicy: Never
        ports:
        - containerPort: 8900
          name: http
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: "standalone"
        - name: JAVA_OPTS
          value: "-Xmx512m -Xms256m"
        - name: EUREKA_CLIENT_ENABLED
          value: "true"
        - name: EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE
          value: "http://service-discovery:8761/eureka/"
        - name: API_GATEWAY_URL
          value: "http://api-gateway:8080"
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /actuator/health
            port: 8900
          initialDelaySeconds: 60
          periodSeconds: 30
        readinessProbe:
          httpGet:
            path: /actuator/health
            port: 8900
          initialDelaySeconds: 30
          periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: proxy-client
  namespace: ecommerce
  labels:
    app: proxy-client
spec:
  type: NodePort
  ports:
  - port: 8900
    targetPort: 8900
    nodePort: 30900
    protocol: TCP
    name: http
  selector:
    app: proxy-client 