apiVersion: apps/v1
kind: Deployment
metadata:
  name: favourite-service
  namespace: ecommerce
  labels:
    app: favourite-service
    version: v1
spec:
  replicas: 2
  selector:
    matchLabels:
      app: favourite-service
  template:
    metadata:
      labels:
        app: favourite-service
        version: v1
    spec:
      containers:
      - name: favourite-service
        image: favourite-service-ecommerce:{{BUILD_NUMBER}}
        imagePullPolicy: Never
        ports:
        - containerPort: 8086
          name: http
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: "standalone"
        - name: JAVA_OPTS
          value: "-Xmx512m -Xms256m"
        - name: EUREKA_CLIENT_ENABLED
          value: "true"
        - name: SERVER_PORT
          value: "8086"
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /actuator/health
            port: 8086
          initialDelaySeconds: 60
          periodSeconds: 30
        readinessProbe:
          httpGet:
            path: /actuator/health
            port: 8086
          initialDelaySeconds: 30
          periodSeconds: 10 