apiVersion: v1
kind: Service
metadata:
  name: favourite-service
  namespace: ecommerce
  labels:
    app: favourite-service
    version: v1
spec:
  type: NodePort
  ports:
  - port: 8086
    targetPort: 8086
    nodePort: 30086
    protocol: TCP
    name: http
  selector:
    app: favourite-service 