apiVersion: v1
kind: ConfigMap
metadata:
  name: user-service-config
  namespace: ecommerce
data:
  application-k8s.yml: |
    server:
      port: 8080
    spring:
      datasource:
        url: jdbc:h2:mem:testdb
        driverClassName: org.h2.Driver
        username: sa
        password: ""
      h2:
        console:
          enabled: true
      jpa:
        hibernate:
          ddl-auto: create-drop
        show-sql: true
    # Deshabilitar Eureka para Kubernetes
    eureka:
      client:
        enabled: false
        service-url:
          defaultZone: http://localhost:8761/eureka
        register-with-eureka: false
        fetch-registry: false
    management:
      endpoints:
        web:
          exposure:
            include: health,info
      endpoint:
        health:
          show-details: always 