apiVersion: v1
kind: Namespace
metadata:
  name: ecommerce
  labels:
    environment: development
    project: ecommerce-microservices
---
apiVersion: v1
kind: Namespace
metadata:
  name: ecommerce-prod
  labels:
    environment: production
    project: ecommerce-microservices 