apiVersion: apps/v1
kind: Deployment
metadata:
  name: shipping-service
  namespace: ecommerce-shipping-dev
  labels:
    app: shipping-service
    version: "{{BUILD_NUMBER}}"
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  selector:
    matchLabels:
      app: shipping-service
  template:
    metadata:
      labels:
        app: shipping-service
        version: "{{BUILD_NUMBER}}"
    spec:
      containers:
      - name: shipping-service
        image: shipping-service-ecommerce:{{BUILD_NUMBER}}
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8085
          name: http
        env:
        - name: SPRING_PROFILES_ACTIVE
          valueFrom:
            configMapKeyRef:
              name: shipping-service-config
              key: SPRING_PROFILES_ACTIVE
        - name: SERVER_PORT
          valueFrom:
            configMapKeyRef:
              name: shipping-service-config
              key: SERVER_PORT
        - name: SPRING_DATASOURCE_URL
          valueFrom:
            configMapKeyRef:
              name: shipping-service-config
              key: SPRING_DATASOURCE_URL
        - name: EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE
          valueFrom:
            configMapKeyRef:
              name: shipping-service-config
              key: EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE
        - name: DB_USERNAME
          valueFrom:
            secretKeyRef:
              name: shipping-service-secrets
              key: DB_USERNAME
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: shipping-service-secrets
              key: DB_PASSWORD
        resources:
          requests:
            memory: "256Mi"
            cpu: "200m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /shipping-service/actuator/health
            port: 8085
          initialDelaySeconds: 120
          periodSeconds: 30
          timeoutSeconds: 10
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /shipping-service/actuator/health/readiness
            port: 8085
          initialDelaySeconds: 60
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        securityContext:
          runAsNonRoot: true
          runAsUser: 1000
          readOnlyRootFilesystem: false
          allowPrivilegeEscalation: false
      restartPolicy: Always
      securityContext:
        fsGroup: 1000 