apiVersion: v1
kind: ConfigMap
metadata:
  name: product-service-config
  namespace: ecommerce
  labels:
    app: product-service
data:
  application.yml: |
    server:
      port: 8082
    
    spring:
      application:
        name: product-service
      datasource:
        url: jdbc:h2:mem:productdb
        driver-class-name: org.h2.Driver
        username: sa
        password: 
      jpa:
        hibernate:
          ddl-auto: create-drop
        show-sql: true
        database-platform: org.hibernate.dialect.H2Dialect
      h2:
        console:
          enabled: true
          path: /h2-console
    
    eureka:
      client:
        service-url:
          defaultZone: http://service-discovery:8761/eureka/
        register-with-eureka: true
        fetch-registry: true
      instance:
        prefer-ip-address: true
        hostname: product-service
    
    management:
      endpoints:
        web:
          exposure:
            include: health,info,metrics,prometheus
      endpoint:
        health:
          show-details: always
          probes:
            enabled: true
      health:
        livenessstate:
          enabled: true
        readinessstate:
          enabled: true
    
    logging:
      level:
        com.selimhorri: DEBUG
        org.springframework.web: DEBUG
      pattern:
        console: "%d{HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"
  
  database-url: "jdbc:h2:mem:productdb"
---
apiVersion: v1
kind: Secret
metadata:
  name: product-service-secrets
  namespace: ecommerce
  labels:
    app: product-service
type: Opaque
data:
  database-username: c2E=  # sa in base64
  database-password: ""     # empty password in base64 