apiVersion: v1
kind: ConfigMap
metadata:
  name: user-service-config
  namespace: ecommerce
data:
  application-k8s.yml: |
    server:
      port: 8700
    
    spring:
      application:
        name: user-service
      datasource:
        url: jdbc:h2:mem:userdb
        driver-class-name: org.h2.Driver
        username: sa
        password: 
      h2:
        console:
          enabled: true
          path: /h2-console
      jpa:
        hibernate:
          ddl-auto: create-drop
        show-sql: true
        properties:
          hibernate:
            format_sql: true
    
    management:
      endpoints:
        web:
          exposure:
            include: health,info,metrics
      endpoint:
        health:
          show-details: always
      health:
        readiness-state:
          enabled: true
        liveness-state:
          enabled: true
    
    logging:
      level:
        com.selimhorri: DEBUG
        org.springframework: INFO 