apiVersion: v1
kind: Service
metadata:
  name: user-service
  namespace: ecommerce-prod
  labels:
    app: user-service
    environment: production
spec:
  type: ClusterIP
  ports:
  - port: 8087
    targetPort: 8087
    protocol: TCP
    name: http
  selector:
    app: user-service
---
apiVersion: v1
kind: Service
metadata:
  name: user-service-lb
  namespace: ecommerce-prod
  labels:
    app: user-service
    type: loadbalancer
    environment: production
spec:
  type: LoadBalancer
  ports:
  - port: 8087
    targetPort: 8087
    protocol: TCP
    name: http
  selector:
    app: user-service 