apiVersion: v1
kind: Service
metadata:
  name: user-service
  namespace: ecommerce
  labels:
    app: user-service
    version: "1.0"
spec:
  type: ClusterIP
  ports:
    - port: 8081
      targetPort: 8081
      protocol: TCP
      name: http
  selector:
    app: user-service
---
apiVersion: v1
kind: Service
metadata:
  name: user-service-lb
  namespace: ecommerce
  labels:
    app: user-service
    type: loadbalancer
spec:
  type: LoadBalancer
  ports:
    - port: 8081
      targetPort: 8081
      protocol: TCP
      name: http
  selector:
    app: user-service 